[workspace]
resolver = "3"
members = ["best-time-to-buy-and-sell-stock", "best-time-to-buy-and-sell-stock-ii","majority-element","merge-sorted-array", "playground", "remove-duplicates-from-sorted-array", "remove-duplicates-from-sorted-array-ii", "remove-element", "rotate-array"]
