[workspace]
resolver = "3"
members = ["majority-element","merge-sorted-array", "playground", "remove-duplicates-from-sorted-array", "remove-duplicates-from-sorted-array-ii", "remove-element", "rotate-array"]
